DROP TABLE IF EXISTS "actions";
CREATE TABLE "actions" ("name" VARCHAR PRIMARY KEY  NOT NULL );
INSERT INTO "actions" VALUES('A_Main');
INSERT INTO "actions" VALUES('A_DeleteUserConfirmation');
INSERT INTO "actions" VALUES('A_SelectRoleToAssignActions');
INSERT INTO "actions" VALUES('A_SearchUsersByName');
INSERT INTO "actions" VALUES('A_SaveActionsForTheRole');
INSERT INTO "actions" VALUES('A_ReadRolesPaginated');
INSERT INTO "actions" VALUES('A_ReadActionsWithStatus');
INSERT INTO "actions" VALUES('A_CreateUser');
INSERT INTO "actions" VALUES('A_Authorize');
INSERT INTO "actions" VALUES('A_UpdateUser');
INSERT INTO "actions" VALUES('A_Authenticate');
INSERT INTO "actions" VALUES('A_CreateRoleForm');
INSERT INTO "actions" VALUES('A_UpdateUserForm');
INSERT INTO "actions" VALUES('A_Null');
INSERT INTO "actions" VALUES('A_DeleteUser');
INSERT INTO "actions" VALUES('A_CreateUserForm');
INSERT INTO "actions" VALUES('A_SelectUserToAssignRoles');
INSERT INTO "actions" VALUES('A_UpdateActions');
INSERT INTO "actions" VALUES('A_ReadAllUsers');
INSERT INTO "actions" VALUES('A_ReadRolesWithStatus');
INSERT INTO "actions" VALUES('A_UpdateRoleForm');
INSERT INTO "actions" VALUES('A_SearchActionsByName');
INSERT INTO "actions" VALUES('A_Logout');
INSERT INTO "actions" VALUES('A_SaveRolesForTheUser');
INSERT INTO "actions" VALUES('A_DeleteRoleConfirmation');
INSERT INTO "actions" VALUES('A_SearchRolesByName');
INSERT INTO "actions" VALUES('A_CreateRole');
INSERT INTO "actions" VALUES('A_UpdateRole');
INSERT INTO "actions" VALUES('A_ReadUsersPaginated');
INSERT INTO "actions" VALUES('A_ReadAllRoles');
INSERT INTO "actions" VALUES('A_DeleteRole');
DROP TABLE IF EXISTS "roles";
CREATE TABLE "roles" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL  UNIQUE , "description" VARCHAR);
INSERT INTO "roles" VALUES(1,'Administrator','Administrative user, has access to everything.');
INSERT INTO "roles" VALUES(2,'Login','Login privileges, granted after account confirmation.');
INSERT INTO "roles" VALUES(3,'Accounting','Mostly access to accounting information.');
DROP TABLE IF EXISTS "roles_actions";
CREATE TABLE "roles_actions" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "role_id" INTEGER NOT NULL , "action_name" VARCHAR NOT NULL );
INSERT INTO "roles_actions" VALUES(262,2,'A_Authenticate');
INSERT INTO "roles_actions" VALUES(263,2,'A_Authorize');
INSERT INTO "roles_actions" VALUES(264,2,'A_ReadUsersPaginated');
DROP TABLE IF EXISTS "users";
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL  UNIQUE , "password" VARCHAR NOT NULL );
INSERT INTO "users" VALUES(1,'admin','$1$.XC9wKL1$Z0qNK1gfEFQdcVD.CBx410');
INSERT INTO "users" VALUES(18,'test01','$6$is44nFIZ7wcf$agdw97JauK8IBWcmT0KAsGmx/0GPcjSF9PKHDY8uRPEkPQp6L9iZoBK6PY1GYHxFDNu.VRRymp//QgX9VXBQX1');
INSERT INTO "users" VALUES(19,'test02','$6$/ltIUBGOCSZO$HGOC0Ir3R6YD.G1kYZgpr5xVlbdb0Z5hMVp.eSS/yp.do8ojkxFtx2kndN3tMurz710vOkmzPokzhhZecUEVH0');
INSERT INTO "users" VALUES(20,'test03','$6$Jt8/SAmdvLSM$DsbiErQ8Cjzsb8.nH3ptGaizb8R4ass2aQ2evexEj9vPhc/Hs6YF9eSFnU84Ve5PSQ6BGo2jrUo5Yypoblr5g.');
INSERT INTO "users" VALUES(21,'test04','$6$tmLMKkbjAQrF$1Y15aKdIdbiL7dokUs3J7uAE1DndJw.FXZ/4HO8gFSnsi.Gt118Z20TdOOLfv2cuYk0g6NWZflfvqnviqSPwB.');
INSERT INTO "users" VALUES(22,'test05','$6$.mMJmyEppP8k$riF5CiE3K6C9Wdv8Ea33ZTlCKy2hnlquO2wDu2EBkMtFwc0.kY1LdBsi/aUWJf1L7GCO2lBgeUqSqpi4qVNiJ/');
INSERT INTO "users" VALUES(23,'test06','$6$3N/4nzOBEujf$fr/JJXmBOqIOQDWhHflo8QgYG189sL3ZdY4cE0inK3.KfJm4152nkjM3/QoYDtrbIOSLsyc1CZc0pjLvjFdfb/');
INSERT INTO "users" VALUES(24,'test07','$6$Ap4zLv7AipZ1$.AmzH66H15vX6LDLV3384B2rVUEH6UIMG1h4eMxMN2SHWI98.vvvQBDEzeiIQLGwot8yqSn2bLL.VagFWW2AE0');
INSERT INTO "users" VALUES(25,'test08','$6$mnUOMztt21oO$qtmJiF3oKjVg4EsfhoHtmO6okn2L5qDF0QOT0ru3Oexu6AuXT0vm58DunqYt3m45.xWpwXYtPoitSvOrVZwHc/');
INSERT INTO "users" VALUES(26,'test09','$6$noMAt8zlkVIw$WwR96eiSNEODULDAxM2JM64l2sd2tlviQYTJZGBBo5leA9/wKTSVqHTZXg3KJQAR0NItv0cqiCAoiSAIDiCNt0');
INSERT INTO "users" VALUES(27,'test10','$6$C9Qd7GTTZRFT$RgTClWYSCYeewBPstQ0FPrmFIsuSAsb1SBpHIinM3RkLimiyLRU4RXC.JP7jBEs/hJ0dhBO0CycfRYdFCSodG1');
INSERT INTO "users" VALUES(28,'test11','$6$cejh3thl6mrQ$GC0HQGYhXlGnzRrdyYEdijPLfjXaExM.8FjGnPhRDCF1IX1zVayTrRv8mfg1JaHKYIvG8WxyZWR8OLieH5p8V/');
INSERT INTO "users" VALUES(29,'test12','$6$nta.iB/z7J9W$yyTac1X1SxumfimMbk5JPCd5nrzibMT9cv83JzsXW1xgqwWyMAwOiwumIzp.TKj24MkkllGG4YzHwYKemqT8C/');
INSERT INTO "users" VALUES(30,'test14','$6$YXT1HApC5FvU$7.oW5Fo4GzogIIZ6MJ9KitHrLzGJanZfCbvNOPhWgucPi6HPnQENzEjJz26C.jMJo5kfx3uFkZSxNlsP5xcAn.');
INSERT INTO "users" VALUES(31,'test13','$6$T.CnoUh1WhYn$3frfkvoSEbMWoBGHcYs2o83q5RrJMAmWpzkATdHIpxpFSNsCdD3oPSsIQffp99.pUKCkRCJW/tB1FtXS0j2.F0');
INSERT INTO "users" VALUES(32,'test15','$6$bkWiRy/Uq8kj$G8SbbRtHnho9Y4mjEKXqGl8GG0Y4zmhFG0TzQlm2s47eAKLeC491azSWtCVhmGOO/CZ/PAPzFmPmRZOn52Yrz0');
INSERT INTO "users" VALUES(33,'test16','$6$Hy0d5dua03Dt$m.r1QGXKdv5IWJoX5E3lxoAcY47iHPNuO34oriIzuGXsixW/q35aWtpRWe48DdT9PqCGt0/3MoUJHBN91cWlM.');
INSERT INTO "users" VALUES(34,'test17','$6$1nW8D30MxF1L$WUKWeBYAVrsMH9gsOVjpHwIsjXcB2p1PWJVZtoGN6vKSVqCs6sQdX0WqtgOGiDZYPMMt1Tcotek3MrZmO4hQ//');
INSERT INTO "users" VALUES(35,'test18','$6$/mRJ0V3I7SdU$YanbgK0T3WUXsmUCc1.OPjSr9LeRbe23C.HVJ/HuSeuarsQaOFwvIz/jwTKJtRbNR6Zk9zSDX9REMg1Nk2piw/');
INSERT INTO "users" VALUES(36,'test19','$6$.0yWsizBCeLM$IIDgAZ1ps741Cf2VB34CxPcgN5528taqnGw1gBCJ0zroANhhnAEzm/gsoanJxUyUrpeuXlrIuEg6ZfhWiOH3B0');
INSERT INTO "users" VALUES(37,'test20','$6$5CrDQHqQ.w4W$vT7eQQLLWxfL1KaJM7dav0aQLPghaxlEtJfpZbK8iFcdHNl6gB4PeLGhkdXn5MDtPml7i.1N8aIYdtFJDgpe/.');
INSERT INTO "users" VALUES(38,'test21','$6$K7fUU2dsrOZ2$bcBcmfrdfRQOXUXctQXOOJJn/x204cxKhWS/hUXa/1u.n1S7g1ASMn7XZn8mjgVW/mfixTk4EWQiYcOYhE0eb/');
DROP TABLE IF EXISTS "users_roles";
CREATE TABLE "users_roles" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "user_id" INTEGER NOT NULL , "role_id" INTEGER NOT NULL );
INSERT INTO "users_roles" VALUES(59,1,1);
INSERT INTO "users_roles" VALUES(81,5,2);
INSERT INTO "users_roles" VALUES(82,15,2);
INSERT INTO "users_roles" VALUES(85,18,2);
